Compile fix for MSVC 2019 as small is seen as a type with some options so this fixes the errors starting with:
code\PostProcessing\ComputeUVMappingProcess.cpp(125): error C2632: 'int' followed by 'char' is illegal